{{- if .Values.mail.enabled }}
  MAIL_ENABLED: "{{ .Values.mail.enabled }}"
  {{- with .Values.mail.smtp }}
  SMTP_HOST: "{{ .host }}"
  SMTP_PORT: "{{ .port }}"
  SMTP_USER: "{{ .user }}"
  SMTP_PASS: "{{ .pass }}"
  FORCE_TRUST_SERVER_CERT: "true"
  {{- end }}
{{- end }}